<a href="https://colab.research.google.com/github/sreekarjallepalli/Data-Science/blob/main/DS_3_3_26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

data = {
    'empid': [101, 102, 103, 104, 105],
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'designation': ['Manager', 'Engineer', 'Analyst', 'Engineer', 'Designer'],
    'years of experience': [10, 5, 3, 7, 2],
    'age': [35, 28, 25, 30, 24],
    'salary': [90000, 70000, 60000, 75000, 55000]
}

employee_df = pd.DataFrame(data)

display(employee_df)

   empid     name designation  years of experience  age  salary
0    101    Alice     Manager                   10   35   90000
1    102      Bob    Engineer                    5   28   70000
2    103  Charlie     Analyst                    3   25   60000
3    104    David    Engineer                    7   30   75000
4    105      Eve    Designer                    2   24   55000

In [ ]:
employee_df = employee_df[employee_df['salary'] >= 10000]

display(employee_df)

   empid     name designation  years of experience  age  salary
0    101    Alice     Manager                   10   35   90000
1    102      Bob    Engineer                    5   28   70000
2    103  Charlie     Analyst                    3   25   60000
3    104    David    Engineer                    7   30   75000
4    105      Eve    Designer                    2   24   55000

In [ ]:
employee_df['designation'].fillna('Unknown', inplace=True)

display(employee_df)

/tmp/ipykernel_411/868736889.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  employee_df['designation'].fillna('Unknown', inplace=True)

   empid     name designation  years of experience  age  salary
0    101    Alice     Manager                   10   35   90000
1    102      Bob    Engineer                    5   28   70000
2    103  Charlie     Analyst                    3   25   60000
3    104    David    Engineer                    7   30   75000
4    105      Eve    Designer                    2   24   55000

In [ ]:
display(employee_df)
employee_df['age'] = employee_df['age'] + 3

   empid     name designation  exp  age  salary
0    101    Alice     Manager   10   38   90000
1    102      Bob    Engineer    5   31   70000
2    103  Charlie     Analyst    3   28   60000
3    104    David    Engineer    7   33   75000
4    105      Eve    Designer    2   27   55000

   empid     name designation  exp  age  salary
0    101    Alice     Manager   10   38   90000
1    102      Bob    Engineer    5   31   70000
2    103  Charlie     Analyst    3   28   60000
3    104    David    Engineer    7   33   75000
4    105      Eve    Designer    2   27   55000